### ISSUE TITLE
Combining two RPs

### ISSUE THREAD

**Issue by andy-portmen** [ecaron/firefox-font-finder#2]
Eric please take a look at my temporary branch
https://github.com/andy-portmen/tmp

If it looks okay,merge it with yours.

**Comment by andy-portmen** [comment]
have you had a chance to take a look at this?

**Comment by ecaron** [comment]
Sorry, I misread your original email.

Would you feel comfortable submitting this as a PR to my repo? Seems like
an excellent opportunity for us to practice that technique.

**Comment by inbasic** [comment]
Combining two comments in one:
(1)
Isn't it easier if you add me as a collaborator first? Also make a beta channel as well. I think it is better if we push to this channel first.
(2)
aslo add Andy to the repo. as well. I just have a single bug fix commit. I can do a pull request if you guys prefer though.

**Comment by inbasic** [comment]
Guys do you want me to change the Github link to Eric's?

**Comment by andy-portmen** [comment]
@ecaron and @inbasic I haven't done any PR before...

**Comment by andy-portmen** [comment]
> Guys do you want me to change the Github link to Eric's?

Not yet please. Let's combine the latest changes first.

**Comment by inbasic** [comment]
@andy-portmen I just sent you an email regarding the bug report. @ecaron there is no need to add me to the repo. anymore.

**Comment by andy-portmen** [comment]
https://github.com/ecaron/firefox-font-finder/pull/3
